### ISSUE TITLE
26 tests failing

### ISSUE THREAD

**Issue by tenorviol** [mutewinter/digest-brunch#20]
Travis is reporting success because the test command reports success. But there are 26 failing tests. https://travis-ci.org/mutewinter/digest-brunch

**Comment by mutewinter** [comment]
Woah, nice catch. Had no idea.

**Comment by mutewinter** [comment]
Was broken by https://github.com/mutewinter/digest-brunch/pull/17

**Comment by tenorviol** [comment]
Do you mean to `-R list`? I tried removing that to no avail. I've been testing like this:

    npm test && echo yay!

If the tests fail, the "yay!" should be suppressed. I think mocha should work with whatever reporter. Actually, I'm at a loss as to why this happens in your repo. I've never seen this issue before.

**Comment by mutewinter** [comment]
Hmm, I don't have time to look into this right now. I put it on my list and I'll look into it when I have time.

**Comment by mutewinter** [comment]
Fixed by #21
