### ISSUE TITLE
digest-brunch breaks html2js and angular templateCache?

### ISSUE THREAD

**Issue by erlandsona** [mutewinter/digest-brunch#26]
My brunch is setup with html2js concatenating my .tpl.html templates into app.js and it creates an "app" module which injects all the templates into the angular templateCache. Everything works perfect until I install digest-brunch. I'm not trying to point fingers, but I can't quite get to the root of the issue... It seems that somehow digest-brunch is deleting a line where the "app" module was getting created by html2js.

I'm assuming this might either be a bug with fs or something but I'm not entirely sure...

I'm using all the latest versions of brunch and plugins.

Any thoughts?

**Comment by mutewinter** [comment]
The only way I can imagine this happening would be if something in the output code contained `DIGEST`.

**Comment by jualoppaz** [comment]
My job partners and me use this plugin in an angular project. All of my partners use linux and get very good results. In my case, I use windows and sometimes the plugin generates the files correctly and other times can't copy all their content and, when the build is finished, you can see the original file (i.e. vendor.js, app.js, ...) and the built file with less content (vendor-37df6a.js, ...). Is it possible that this plugin or some of its dependencies doesn't work correctly in windows?

Thank you for your time.

**Comment by acautin** [comment]
@jualoppaz you should create a separate issue next time easier to see your problem.

Now what you describe is the same problem I had when having many files and sometimes brunch would take a long time to process the list, this plugin was called more than once with an incomplete ``app.js`` file which was then renamed, as a workaround I have increased the [fileListInterval](http://brunch.io/docs/config) in my brunch-config to a very high number: 

```
fileListInterval: 1000,
```
I hope it helps.

**Comment by jualoppaz** [comment]
The fileListInterval param resolved my problem. Thank you so much @acautin .

**Comment by mutewinter** [comment]
Closing this since it sounds like it got resolved!
