### ISSUE TITLE
Wrong path separator under Windows

### ISSUE THREAD

**Issue by hipertracker** [mutewinter/digest-brunch#28]
Digest paths generated in Windows contain **backslash** instead of **slash** for path separator. The code should never ever use the backslash. Slash is also a perfect, valid path folder separator in Windows.

**Comment by mutewinter** [comment]
I'm not actively using this project, but I'll happily review a pull request that fixes this.

**Comment by youpiwaza** [comment]
Do you have an update on this ?
I got the problem when using DIGEST() in react. Oddly enough I don't have the problem when using an image directly on the html

**Comment by matt-harvey** [comment]
Looks like this is fixed in v1.6.0? See https://github.com/mutewinter/digest-brunch/pull/30.

**Comment by mutewinter** [comment]
Yeah, seems fixed. Closing, but @ me if I should reopen.
