### ISSUE TITLE
Why moved to Webpack?

### ISSUE THREAD

**Issue by r3verser** [mutewinter/digest-brunch#34]
Hi, im new to brunch js and don't know any future pitfalls with it, can you explain why you switched to webpack, so i could decide to continue with brunch on my new project!

**Comment by mutewinter** [comment]
Here's a good rundown https://www.slant.co/versus/4231/11602/~brunch_vs_webpack.

I haven't used Brunch in years at this point. Webpack is where the community has moved (at least for React, which is what I'm using now).
