### ISSUE TITLE
Not replece DIGEST markers in inner files - recursion

### ISSUE THREAD

**Issue by wziebicki** [mutewinter/digest-brunch#7]
Hi!

For example if i have following files:

- index.html
  &lt;div class="row line contentspacing center footer" ng-include src="'DIGEST(inner.html)'" 	&gt;&lt;/div 	&gt;

- inner.html
  &lt;div class="row line contentspacing center footer" ng-include src="'DIGEST(inner2.html)'" 	&gt;&lt;/div 	&gt;

DIGEST maker in inner2.html is not replaced

**Comment by mutewinter** [comment]
Fixed by `1.5.0`.
