### ISSUE TITLE
Rewrite Based on Manifest File

### ISSUE THREAD

**Issue by mutewinter** [mutewinter/digest-brunch#8]
Renaming and replacing occurrences of `DIGEST` ad-hoc was a bad approach. Instead, we should generate a manifest file a la Rails and then do the rename / replacements based on its contents. We could optionally leave the manifest file around as an artifact that allows 

Examples in the wild:

* https://github.com/zendesk/grunt-digest
* http://guides.rubyonrails.org/asset_pipeline.html#manifest-files-and-directives

**Comment by mutewinter** [comment]
Closed by #24

**Comment by solisoft** [comment]
How does it works?  How can I set the digest as parameter ?
